### PR TITLE
[JENKINS-74063][JENKINS-74064][JENKINS-74065][JENKINS-74066] Fix CSP issues

### PR DESCRIPTION
**Pull request by yaroslavafenkin**
https://issues.jenkins.io/browse/JENKINS-74063
https://issues.jenkins.io/browse/JENKINS-74064
https://issues.jenkins.io/browse/JENKINS-74065
https://issues.jenkins.io/browse/JENKINS-74066

### Testing done

[Before the change](https://www.youtube.com/watch?v=tVzRJUkmzxA)
[After the change](https://www.youtube.com/watch?v=CITSj05egMA)

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by basil — COMMENTED** [review]
This code is very similar to https://github.com/jenkinsci/cloudbees-disk-usage-simple-plugin/pull/113/files and in that PR I was able to clean up the error handling to only show the notification on success (and show a different one on failure) as well as to use the notification bar to show proper colors. Perhaps we could apply the same cleanup here? I know it isn't strictly necessary, but it seems trivial to do so and I think would establish a pattern of consistency throughout this project if we always handle the same original code with the same fix.

**Comment by yaroslavafenkin** [comment]
> This code is very similar to https://github.com/jenkinsci/cloudbees-disk-usage-simple-plugin/pull/113/files and in that PR I was able to clean up the error handling to only show the notification on success (and show a different one on failure) as well as to use the notification bar to show proper colors. Perhaps we could apply the same cleanup here? I know it isn't strictly necessary, but it seems trivial to do so and I think would establish a pattern of consistency throughout this project if we always handle the same original code with the same fix.

Sure, I'll handle it.

**Comment by yaroslavafenkin** [comment]
Looks much better now.
image
image

**Review by basil — APPROVED** [review]
Thanks!

**Comment by basil** [comment]
@MarkEWaite Are you interested in doing a release?

**Comment by MarkEWaite** [comment]
Released as [2.7](https://github.com/jenkinsci/ivy-plugin/releases/tag/ivy-2.7)

**Pull request merged**
